version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: muni123
      POSTGRES_PASSWORD: muni123
      POSTGRES_DB: muni_test
    ports:
      - "5432:5432"
    volumes:
      - ./docker_data/posgres_data:/var/lib/postgresql/data
  pgadmin:
    container_name: "pgadmin_container"
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: muni@gmail.com
      PGADMIN_DEFAULT_PASSWORD: muni123
    ports:
      - "5050:80"
    volumes:
      - ./docker_data/pgadmin_data:/var/lib/pgadminfr