defaults:
  - _self_
  - data_saver@sqlite_saver: sqlite_saver
  - data_saver@csv_saver: csv_saver
  - data_saver@jsonl_saver: jsonl_saver

data_saver:
  - csv_saver: ${csv_saver}
  - jsonl_saver: ${jsonl_saver}
  - sqlite_saver: ${sqlite_saver}

hydra:  
  output_subdir: null  
  run:  
    dir: .